import { createSlice } from '@reduxjs/toolkit';
import { createSelector } from 'reselect';
import { BOARDGAMES } from '../../app/shared/BOARDGAMES';

const initialState = {
    boardgamesArray: BOARDGAMES
}

const boardgamesSlice = createSlice({
    name: 'boardgames',
    initialState
    // reducers: 
    
});

// boardgamesReducer is a reducer function generated by the createSlice function. It combines the reducer logic defined in the reducers object and the initial state into a single reducer function.
export const boardgamesReducer = boardgamesSlice.reducer;

// These selector functions take the entire Redux state as an argument, represented by the (state) parameter. The selector function then accesses the relevant part of the state and returns the desired data.

export const selectAllBoardgames = (state) => {
    return state.boardgames.boardgamesArray;
}

export const selectBoardgameById = (id) => createSelector(
    (state) => state.boardgames.boardgamesArray,
    (boardgamesArray) => {
        return boardgamesArray.find((game) => game.id === parseInt(id));
    }
);

export const selectRandomBoardgame = createSelector(
    (state) => state.boardgames.boardgamesArray,
    (boardgamesArray) => {
        return boardgamesArray[ Math.floor(Math.random() * BOARDGAMES.length) ];
    }
);